"""
Link Extractor Module

This module extracts car advertisement links from OLX.uz by processing
price ranges. It systematically scrapes listing pages for each price range,
collects all car advertisement URLs, and saves them to output files.

The module processes price ranges from a JSON file (typically generated by
range_finder.py) and extracts links by:

- Iterating through all pages for each price range
- Parsing HTML to find car advertisement links
- Deduplicating links to avoid duplicates
- Detecting pagination end conditions
- Tracking progress and saving incrementally

Features:
- Handles pagination automatically
- Detects end of pagination when no new links are found
- Saves progress after each price range to prevent data loss
- Outputs to both text (one link per line) and JSON formats
- Includes metadata (timestamp, progress, total count) in JSON output
- Rate limiting with delays between requests

Output Files:
- car_links.txt: Plain text file with one URL per line
- car_links.json: JSON file with links and metadata

Usage:
    python link_extractor.py

The script expects 'price_ranges.json' in the same directory.
"""

import requests
import lxml
from bs4 import BeautifulSoup
import time
import json
import datetime
import re
import os

def process_price_ranges(price_ranges_file, output_file_txt=None, output_file_json=None):
    """
    Process a file of price ranges and extract links from each range.
    
    Args:
        price_ranges_file: Path to the JSON file containing price ranges
        output_file_txt: Path to save links as text file (one link per line)
        output_file_json: Path to save links and metadata as JSON
    
    Returns:
        List of extracted links
    """
    # Load price ranges
    with open(price_ranges_file, 'r') as f:
        ranges_data = json.load(f)
    
    price_ranges = ranges_data["price_ranges"]
    print(f"Loaded {len(price_ranges)} price ranges from {price_ranges_file}")
    
    # Initialize
    base_url = 'https://www.olx.uz/transport/legkovye-avtomobili/'    
    page_links = []
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
    }
    
    # Process each price range
    total_ranges = len(price_ranges)
    for i, (min_price, max_price) in enumerate(price_ranges):
        print(f"\nProcessing price range {i+1}/{total_ranges}: {min_price} to {max_price}")
        process_price_range(base_url, headers, min_price, max_price, page_links)
        
        # Print progress update
        print(f"Progress: {i+1}/{total_ranges} price ranges completed ({((i+1)/total_ranges)*100:.1f}%)")
        print(f"Links collected so far: {len(page_links)}")
        
        # Update progress in the main files after each range
        update_progress_in_files(page_links, i+1, total_ranges, price_ranges[:i+1], output_file_txt, output_file_json)
        
        # Longer pause between price ranges
        if i < len(price_ranges) - 1:
            print(f"Pausing between price ranges...")
            time.sleep(5)  # 5 second delay between price ranges

    # Print summary
    print(f"\nTotal links collected from all pages and price ranges: {len(page_links)}")
    print(f"First 5 links:")
    for i, link in enumerate(page_links[:5]):
        print(f"  {i+1}: {link}")

    print(f"Last 5 links:")
    for i, link in enumerate(page_links[-5:]):
        print(f"  {len(page_links)-4+i}: {link}")
    
    # The final files have already been updated during the process
    print(f"All links have been saved to {output_file_txt} and {output_file_json}")
    
    return page_links


def process_price_range(base_url, headers, min_price, max_price, page_links, max_pages=50):
    """Process all pages for a given price range"""
    print(f"\n--- Processing price range: {min_price} to {max_price} ---")
    
    initial_link_count = len(page_links)
    page_num = 1
    has_more_pages = True
    total_count = None
    consecutive_no_new_links = 0  # Counter for pages with no new links
    
    while has_more_pages and page_num <= max_pages:
        # Construct URL with price filter and page number
        if page_num == 1:
            page_param = ""
            display_page = 1
        else:
            page_param = f"&page={page_num}"
            display_page = page_num
            
        url = f"{base_url}?currency=UYE{page_param}&search%5Bfilter_float_price%3Afrom%5D={min_price}&search%5Bfilter_float_price%3Ato%5D={max_price}&search%5Border%5D=filter_float_price%3Adesc"
        
        links_before = len(page_links)
        success, has_more_pages, page_total_count = scrape_page(url, headers, page_links, display_page)
        links_after = len(page_links)
        new_links_found = links_after - links_before
        
        # Update total count if we got a value
        if page_total_count is not None:
            total_count = page_total_count
        
        if not success:
            print(f"Failed to scrape page {display_page} for price range {min_price}-{max_price}")
            break
            
        # If no new links were found, we may have reached the end of pagination or seeing repeated content
        if new_links_found == 0:
            consecutive_no_new_links += 1
            print(f"No new links found on page {display_page} - may be seeing repeated content")
            
            # If we've had 2 consecutive pages with no new links, stop pagination
            if consecutive_no_new_links >= 2:
                print(f"Detected end of unique content after {consecutive_no_new_links} pages with no new links")
                has_more_pages = False
                break
        else:
            # Reset counter if we found new links
            consecutive_no_new_links = 0
        
        # Move to next page
        page_num += 1
        
        # Add a delay to avoid being blocked
        if has_more_pages:
            print(f"Waiting before fetching next page...")
            time.sleep(2)  # 2 second delay between requests
    
    links_added = len(page_links) - initial_link_count
    print(f"Completed processing price range {min_price}-{max_price}, processed {page_num-1} pages")
    print(f"Links found in this price range: {links_added}")
    print(f"Total links collected so far: {len(page_links)}")
    
    return total_count


def scrape_page(page_url, headers, page_links, page_num=None):
    """Scrape a single page and extract links"""
    try:
        # Sending the GET request with headers and a timeout
        print(f"Fetching: page {page_num if page_num is not None else '?'}")
        response = requests.get(page_url, headers=headers, timeout=10)  # timeout in seconds

        # Checking if the request was successful (status code 200 OK)
        response.raise_for_status()  # Raises an HTTPError for bad responses (4xx or 5xx)

        print(f"Successfully fetched page {page_num if page_num is not None else '?'}")
        # Now you can access the content
        html_content = response.text  # Get the HTML content as a string

        # Parse HTML with BeautifulSoup
        soup = BeautifulSoup(html_content, 'lxml')
        
        # Find all elements with the target class
        elements = soup.find_all(class_='css-1tqlkj0')
        
        print(f"Found {len(elements)} elements with class 'css-1tqlkj0' on page {page_num if page_num is not None else '?'}")
        
        # Check if no elements were found - could indicate we've gone beyond available pages
        if len(elements) == 0:
            print(f"No elements found on page {page_num if page_num is not None else '?'} - may be beyond available pages")
            return False, False, None  # (success, has_more_pages, total_count)
        
        # Extract links and add to page_links
        page_count = 0
        found_new_links = False
        for element in elements[::2]:  # Skip every second element
            href = element.get('href')
            if href:
                complete_url = "https://olx.uz" + href
                if complete_url not in page_links:  # Avoid duplicates
                    page_links.append(complete_url)
                    page_count += 1
                    found_new_links = True
        
        print(f"Added {page_count} links from page {page_num if page_num is not None else '?'}")
        
        # If all links were already in our collection, this might be a duplicate/recycled page
        if not found_new_links and len(elements) > 0:
            print(f"All links on page {page_num if page_num is not None else '?'} were already in our collection")
            # We don't immediately stop pagination here, but the caller will track consecutive pages with no new links
        
        # Extract total count
        total_count_element = soup.find('span', attrs={'data-testid': 'total-count'})
        total_count = None
        if total_count_element:
            count_text = total_count_element.text.strip()
            print(f"Found total count text: {count_text}")
            
            # Parse the count text which might contain &nbsp; or spaces
            # Remove all non-digit characters and convert to int
            count_text = re.sub(r'\D', '', count_text)
            if count_text:
                total_count = int(count_text)
                print(f"Parsed total count: {total_count}")
            
            # Check if it's showing "1 000" which means it's over the limit
            if "1" in total_count_element.text and ("000" in total_count_element.text or "nbsp" in str(total_count_element)):
                print("DETECTED: Count is at or over 1000 post limit!")
                total_count = 1000
        
        # Check if we got redirected to a different page number
        # This helps detect when we've reached the end of pagination
        current_page_indicator = page_url.split('page=')
        if len(current_page_indicator) > 1:
            requested_page = current_page_indicator[1].split('&')[0]
            
            # Check if there's pagination info in the HTML
            pagination_elements = soup.find_all(class_='css-1mi714g')  # Adjust class as needed
            if pagination_elements:
                # If no pagination elements or we were redirected, we might be at the end
                print(f"Found pagination elements: {len(pagination_elements)}")
                return True, True, total_count  # Success and has more pages
            
            # Alternative check - if we got very few results, might be the last page
            if len(elements) < 10:
                print("Few elements found - might be last page")
                return True, False, total_count
        
        return True, True, total_count  # Success and possibly has more pages
        
    except requests.exceptions.Timeout:
        print(f"Request timed out for {page_url}")
        return False, False, None
    except requests.exceptions.HTTPError as errh:
        # If we get a 404, it means we've gone beyond available pages
        if errh.response.status_code == 404:
            print(f"Page not found (404) - reached end of pagination")
            return False, False, None
        print(f"Http Error: {errh} (Status code: {errh.response.status_code})")
        return False, False, None
    except requests.exceptions.RequestException as err:
        print(f"Something went wrong fetching {page_url}: {err}")
        return False, False, None


def update_progress_in_files(links, range_index, total_ranges, completed_ranges, txt_file=None, json_file=None):
    """Update the main files with current progress after each range"""
    if not txt_file and not json_file:
        return
    
    # Update text file
    if txt_file:
        with open(txt_file, 'w') as f:
            for link in links:
                f.write(f"{link}\n")
        print(f"Updated {txt_file} with {len(links)} links")
    
    # Update JSON file
    if json_file:
        json_data = {
            "timestamp": datetime.datetime.now().isoformat(),
            "progress": f"{range_index}/{total_ranges}",
            "progress_percent": f"{((range_index)/total_ranges)*100:.1f}%",
            "total_links": len(links),
            "completed_ranges": completed_ranges,
            "links": links
        }
        with open(json_file, 'w', encoding='utf-8') as f:
            json.dump(json_data, f, indent=2)
        print(f"Updated {json_file} with {len(links)} links and progress information")


if __name__ == "__main__":
    # Example usage
    ranges_file = "price_ranges.json"
    output_txt = "car_links.txt"
    output_json = "car_links.json"
    
    if os.path.exists(ranges_file):
        process_price_ranges(ranges_file, output_txt, output_json)
    else:
        print(f"Error: Price ranges file '{ranges_file}' not found.")
        print("Please run the price range determination script first to generate this file.") 